### PR TITLE
Upgraded BabySmash to .NET 5

### PR DESCRIPTION
**Pull request by cathysull**
Used the [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant) to upgrade BabySmash to .NET 5.

### CODE REVIEW

**Comment by cathysull** [comment]
@shanselman - Olia and I prepared a PR that upgrades the app to .NET 5. We disabled signing for the ClickOnce manifest. She will help prepare the ClickOnce once we get this PR merged in. Take a look.

**Comment by shanselman** [comment]
Do we want this in MAIN MAIN or maybe in its own dotnet5 branch?

**Comment by cathysull** [comment]
Great question, were thinking of having it as a dotnet5 branch, that way we'd could still use the original (main branch) to demo upgrades. What are your thoughts?

**Comment by shanselman** [comment]
I just need to figure out how to merge your PR in...but not into Main.

**Comment by cathysull** [comment]
Sounds good. Let me know if I can help!

**Review by shanselman — APPROVED** [review]
I need to get a cert I guess! 👍🏻

**Pull request merged**
