### PR TITLE
Ovals, upgrade sln, autoformatting cleanup, readme.md, hardware effects, and word combines!

### PR DESCRIPTION
**Pull request by DavidRieman**

### CODE REVIEW

**Comment by shanselman** [comment]
Sorry, just saw this, will take a look asap. Also @ericlaw1979 may be interested as well. The autoformatting isn't interesting but the Words mod is what's cool. We should find a default kid-friendly dictionary. This mod was on my list for years.

**Comment by DavidRieman** [comment]
I actually forked from his, and made a PR for him as well.

**Comment by shanselman** [comment]
Just an FYI so you don't thinking I'm ignoring you. I am going to look at this and take it in, but first I need to figure out how to re-release BabySmash. It is quiet stable and has a tens of thousands of users, so I need to make sure that I can put it out again as ClickOnce (or we change it to use Squirrel?) and not break the world.

**Comment by ericlaw1979** [comment]
If we simply need to re-sign the bits with Authenticode, I've got a trusted-by-SmartScreen certificate for that already if Scott doesn't have one himself.

**Comment by shanselman** [comment]
Ya, let's you and I pair and do some testing next week Eric? Got any time
during work hours on Monday?

On Fri, Apr 3, 2015 at 2:23 PM, Eric Lawrence <notifications@github.com>
wrote:

> If we simply need to re-sign the bits with Authenticode, I've got a
> trusted-by-SmartScreen certificate for that already if Scott doesn't have
> one himself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/babysmash/pull/3#issuecomment-89424065>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by ericlaw1979** [comment]
@shanselman Sure, Monday works for me, 10a-3p CDT?

**Comment by shanselman** [comment]
Crap, I just saw this. Timezones.

Do you have any time between 1pm and 3pm on Weds PST?

On Sat, Apr 4, 2015 at 2:03 PM, Eric Lawrence <notifications@github.com>
wrote:

> @shanselman <https://github.com/shanselman> Sure, Monday works for me,
> 10a-3p CDT?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/babysmash/pull/3#issuecomment-89667774>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by ericlaw1979** [comment]
Sure, 3pm CDT/1pm PDT works for me

**Comment by shanselman** [comment]
Cool, I'm glucopilot on Skype. Talk then.

On Wed, Apr 8, 2015 at 6:40 AM, Eric Lawrence <notifications@github.com>
wrote:

> Sure, 3pm CDT/1pm PDT works for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/babysmash/pull/3#issuecomment-90919396>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Pull request merged**
